### ISSUE TITLE
bug: Does not compile using rustc 1.87

### ISSUE THREAD

**Issue by lrodziewicz** [MalpenZibo/ashell#273]
Hi,
I have tried installing ashell (both non, and `-git` versions) on arch using yay but got following errors:
```
error[E0658]: `let` expressions in this position are unstable
  --> src/modules/privacy.rs:39:12
   |
39 |         if let Some(service) = self.service.as_ref()
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> src/modules/settings/bluetooth.rs:102:12
    |
102 |         if let Some(service) = &self.service
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> src/outputs.rs:361:16
    |
361 |             if let Some(shell_info) = shell_info
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> src/outputs.rs:385:16
    |
385 |             if let Some(shell_info) = shell_info
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ashell` (bin "ashell") due to 4 previous errors
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: ashell-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
ashell-git - exit status 4
```

I suspect that it's because chaining let is only stable in rust 1.88 and I'm using 1.87.0 but I haven't investigated it any further.
```
╰─➤  rustc --version                                                                                         1 ↵
rustc 1.87.0 (17067e9ac 2025-05-09)
```

While the repo `Cargo.toml` set it `1.85.0` at the time of writing.

**Comment by MalpenZibo** [comment]
You're probably right. I didn't notice this problem. I have to update the version in the `Cargo.toml` file.

Are you able to update your rust version?

**Comment by lrodziewicz** [comment]
I can confirm it compiles after updating to `1.88.0` 👍
